framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
        cookie_lifetime: 1209600
        cookie_secure: auto
        storage_factory_id: session.storage.factory.native
    esi: true
    fragments: true
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/%bolt.public_folder%/assets/manifest.json'
    cache:
        prefix_seed: bolt
    ide: phpstorm
    validation:
        email_validation_mode: html5
        enable_annotations: true
    translator:
        paths:
            - '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/vendor/bolt/core/translations'
    error_controller: 'Bolt\Controller\ErrorController::showAction'
