version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bolt
      - MYSQL_USER=bolt
      - MYSQL_PASSWORD=rolandAPI
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        
  # h2-proxy:
  #   build:
  #     context: ./docker/h2-proxy
  #   depends_on:
  #     - nginx
  #   ports:
  #     - target: 8443
  #       published: 8443
  #       protocol: tcp

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - target: 1080
        published: 1080
        protocol: tcp

