version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bolt
      - MYSQL_USER=bolt
      - MYSQL_PASSWORD=rolandAPI
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  nginx:
    build:
      context: ./
      dockerfile: Dockerfileprod
      target: nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/bolt/public:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - target: 443
        published: 8443
        protocol: tcp
      - target: 80
        published: 8080
        protocol: tcp
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email roland.antonius@gmail.com -d localhost --agree-tos
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - target: 1080
        published: 1080
        protocol: tcp

