version: '3.4'

services:

  php:
    build:
      context: ./
      dockerfile: Dockerfileprod
      target: php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./:/srv/bolt:rw,cached
      - ./docker/php/conf.d/bolt.dev.ini:/usr/local/etc/php/conf.d/bolt.ini

  nginx:
    build:
      context: ./
      dockerfile: Dockerfileprod
      target: nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/bolt/public:rw
      - ./certbot/www:/srv/bolt/public/certbot
      - ./certbot/conf:/etc/nginx/ssl
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/srv/bolt/public/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /srv/bolt/public/certbot --force-renewal --email roland.antonius@gmail.com -d codebyjedi.com --agree-tos
