assignable_roles:
    - ROLE_ADMIN
    - ROLE_EDITOR
    - ROLE_DEVELOPER
    - ROLE_CHIEF_EDITOR
    - ROLE_USER
global:
    about:
        - IS_AUTHENTICATED_ANONYMOUSLY
        - ROLE_EDITOR
    clearcache:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    dashboard:
        - IS_AUTHENTICATED_FULLY
        - IS_AUTHENTICATED_REMEMBERED
    extensions:
        - ROLE_ADMIN
    'managefiles:config':
        - ROLE_ADMIN
    'managefiles:files':
        - ROLE_ADMIN
        - ROLE_EDITOR
    'managefiles:themes':
        - ROLE_ADMIN
    editprofile:
        - IS_AUTHENTICATED_FULLY
    translation:
        - ROLE_ADMIN
    'user:list':
        - ROLE_ADMIN
    'user:add':
        - ROLE_ADMIN
    'user:status':
        - ROLE_ADMIN
    'user:delete':
        - ROLE_ADMIN
    'user:edit':
        - ROLE_ADMIN
    systemlog:
        - ROLE_ADMIN
    api_admin:
        - ROLE_ADMIN
    bulk_operations:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    kitchensink:
        - ROLE_ADMIN
    upload:
        - ROLE_EDITOR
    extensionmenus:
        - IS_AUTHENTICATED_FULLY
        - IS_AUTHENTICATED_REMEMBERED
    maintenance-mode:
        - ROLE_EDITOR
    media_edit:
        - ROLE_EDITOR
    fetch_embed_data:
        - ROLE_EDITOR
    'list_files:config':
        - ROLE_ADMIN
    'list_files:files':
        - ROLE_EDITOR
    'list_files:themes':
        - ROLE_ADMIN
contenttype-base:
    edit:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    create:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    change-status:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    delete:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    change-ownership:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
    view:
        - ROLE_ADMIN
        - ROLE_CHIEF_EDITOR
contenttype-default:
    edit:
        - ROLE_EDITOR
        - CONTENT_OWNER
    create:
        - ROLE_EDITOR
    change-ownership:
        - CONTENT_OWNER
    view:
        - ROLE_EDITOR
contenttypes: ~
